title: "andreinc"
title_separator: "|"
subtitle: "Personal blog of Andrei N. Ciobanu"
email: none@none.com
description: >-
  Personal blog of Andrei N. Ciobanu.
baseurl: "" 
url: ""
breadcrumbs: false
github_username:  nomemory

# Build settings  
theme: minimal-mistakes-jekyll
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-email-protect

minimal_mistakes_skin: air # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

compress_html:
  clippings: all

include: ["_pages"]

author:
  name: "Andrei Ciobanu"
  avatar: "/assets/images/me.jpg"
  bio: >-
    A random software engineer from Eastern Europe.
  location: "Bucharest, Romania"
  links:
    - label: GitHub
      icon: "fab fa-fw fa-github"
      url: "https://github.com/nomemory"
    - label: LinkedIn
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andrei-n-ciobanu-50708611/"
    - label: Spotify
      icon: "fab fa-fw fa-spotify"
      url: "https://open.spotify.com/user/a3dud6s6igdiphj760chzhpxv?si=haRc0m-YQEqrPQVNbGxAEA"

repository: "nomemory/andreinc-site"
comments:
  provider: "utterances"
  utterances:
    repo:  "nomemory/andreinc-site"
    theme: "github-light" # "github-dark"
    issue_term: "pathname"


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: false
      comments: true
      share: true
      related: false
      excerpt: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

permalink: /:year/:month/:day/:title